var age;
age = 30;
console.log({ age: age });
age = ["20"];
console.log({ age: age });
age = true;
console.log({ age: age });
var mixed = [];
mixed.push("mario");
mixed.push(true);
mixed.push(20);
console.log({ mixed: mixed });
var ninja;
ninja = { name: "yoshi", age: 15 };
console.log({ ninja: ninja });
ninja = { name: 10, age: true };
console.log({ ninja: ninja });
